#ifndef RETROPHIES_EMITTER_H
#define RETROPHIES_EMITTER_H

#include <stdint.h>
#include <stdarg.h>

enum
{
  /* 1-byte */
  RETROPHIES_INSN_ABS_I32,
  RETROPHIES_INSN_ABS_I64,
  RETROPHIES_INSN_ABS_F32,
  RETROPHIES_INSN_ABS_F64,
  RETROPHIES_INSN_ADD_I32,
  RETROPHIES_INSN_ADD_I64,
  RETROPHIES_INSN_ADD_F32,
  RETROPHIES_INSN_ADD_F64,
  RETROPHIES_INSN_AND,
  RETROPHIES_INSN_AND_I32,
  RETROPHIES_INSN_AND_I64,
  RETROPHIES_INSN_CEIL_F32,
  RETROPHIES_INSN_CEIL_F64,
  RETROPHIES_INSN_DIV_I32,
  RETROPHIES_INSN_DIV_I64,
  RETROPHIES_INSN_DIV_U32,
  RETROPHIES_INSN_DIV_U64,
  RETROPHIES_INSN_DIV_F32,
  RETROPHIES_INSN_DIV_F64,
  RETROPHIES_INSN_EQUAL_I32,
  RETROPHIES_INSN_EQUAL_I64,
  RETROPHIES_INSN_EQUAL_U32,
  RETROPHIES_INSN_EQUAL_U64,
  RETROPHIES_INSN_EQUAL_F32,
  RETROPHIES_INSN_EQUAL_F64,
  RETROPHIES_INSN_FLOOR_F32,
  RETROPHIES_INSN_FLOOR_F64,
  RETROPHIES_INSN_GREATEREQUAL_I32,
  RETROPHIES_INSN_GREATEREQUAL_I64,
  RETROPHIES_INSN_GREATEREQUAL_U32,
  RETROPHIES_INSN_GREATEREQUAL_U64,
  RETROPHIES_INSN_GREATEREQUAL_F32,
  RETROPHIES_INSN_GREATEREQUAL_F64,
  RETROPHIES_INSN_GREATERTHAN_I32,
  RETROPHIES_INSN_GREATERTHAN_I64,
  RETROPHIES_INSN_GREATERTHAN_U32,
  RETROPHIES_INSN_GREATERTHAN_U64,
  RETROPHIES_INSN_GREATERTHAN_F32,
  RETROPHIES_INSN_GREATERTHAN_F64,
  RETROPHIES_INSN_IDIV_I32,
  RETROPHIES_INSN_IDIV_I64,
  RETROPHIES_INSN_IDIV_U32,
  RETROPHIES_INSN_IDIV_U64,
  RETROPHIES_INSN_LESSEQUAL_I32,
  RETROPHIES_INSN_LESSEQUAL_I64,
  RETROPHIES_INSN_LESSEQUAL_U32,
  RETROPHIES_INSN_LESSEQUAL_U64,
  RETROPHIES_INSN_LESSEQUAL_F32,
  RETROPHIES_INSN_LESSEQUAL_F64,
  RETROPHIES_INSN_LESSTHAN_I32,
  RETROPHIES_INSN_LESSTHAN_I64,
  RETROPHIES_INSN_LESSTHAN_U32,
  RETROPHIES_INSN_LESSTHAN_U64,
  RETROPHIES_INSN_LESSTHAN_F32,
  RETROPHIES_INSN_LESSTHAN_F64,
  RETROPHIES_INSN_MOD_I32,
  RETROPHIES_INSN_MOD_I64,
  RETROPHIES_INSN_MOD_U32,
  RETROPHIES_INSN_MOD_U64,
  RETROPHIES_INSN_MOD_F32,
  RETROPHIES_INSN_MOD_F64,
  RETROPHIES_INSN_MUL_I32,
  RETROPHIES_INSN_MUL_I64,
  RETROPHIES_INSN_MUL_F32,
  RETROPHIES_INSN_MUL_F64,
  RETROPHIES_INSN_NEG_I32,
  RETROPHIES_INSN_NEG_I64,
  RETROPHIES_INSN_NEG_F32,
  RETROPHIES_INSN_NEG_F64,
  RETROPHIES_INSN_NOT,
  RETROPHIES_INSN_NOTEQUAL_I32,
  RETROPHIES_INSN_NOTEQUAL_I64,
  RETROPHIES_INSN_NOTEQUAL_U32,
  RETROPHIES_INSN_NOTEQUAL_U64,
  RETROPHIES_INSN_NOTEQUAL_F32,
  RETROPHIES_INSN_NOTEQUAL_F64,
  RETROPHIES_INSN_OR,
  RETROPHIES_INSN_OR_I32,
  RETROPHIES_INSN_OR_I64,
  RETROPHIES_INSN_PUSH_0,
  RETROPHIES_INSN_PUSH_1,
  RETROPHIES_INSN_PUSH_2,
  RETROPHIES_INSN_PUSH_10,
  RETROPHIES_INSN_PUSH_16,
  RETROPHIES_INSN_PUSH_I8,
  RETROPHIES_INSN_PUSH_I16,
  RETROPHIES_INSN_PUSH_I32,
  RETROPHIES_INSN_PUSH_I64,
  RETROPHIES_INSN_PUSH_U8,
  RETROPHIES_INSN_PUSH_U16,
  RETROPHIES_INSN_PUSH_U32,
  RETROPHIES_INSN_PUSH_U64,
  RETROPHIES_INSN_PUSH_F32,
  RETROPHIES_INSN_PUSH_F64,
  RETROPHIES_INSN_RAND_U32,
  RETROPHIES_INSN_RAND_F32,
  RETROPHIES_INSN_RANDOMIZE,
  RETROPHIES_INSN_RETURN,
  RETROPHIES_INSN_SHIFTLEFT_I32,
  RETROPHIES_INSN_SHIFTLEFT_I64,
  RETROPHIES_INSN_SHIFTRIGHT_I32,
  RETROPHIES_INSN_SHIFTRIGHT_I64,
  RETROPHIES_INSN_SHIFTRIGHT_U32,
  RETROPHIES_INSN_SHIFTRIGHT_U64,
  RETROPHIES_INSN_SUB_I32,
  RETROPHIES_INSN_SUB_I64,
  RETROPHIES_INSN_SUB_F32,
  RETROPHIES_INSN_SUB_F64,
  RETROPHIES_INSN_TRUNC_F32,
  RETROPHIES_INSN_TRUNC_F64,
  RETROPHIES_INSN_XOR_I32,
  RETROPHIES_INSN_XOR_I64,

  RETROPHIES_INSN_LAST_1BYTE,

  /* 3-bytes */
  RETROPHIES_INSN_GETGLOBAL,
  RETROPHIES_INSN_GETLOCAL,
  RETROPHIES_INSN_SETGLOBAL,
  RETROPHIES_INSN_SETLOCAL,

  RETROPHIES_INSN_LAST_3BYTES,

  /* 5-bytes */
  RETROPHIES_INSN_CALL,
  RETROPHIES_INSN_JE,
  RETROPHIES_INSN_JNE,
  RETROPHIES_INSN_JUMP,
  RETROPHIES_INSN_NEXT,

  RETROPHIES_INSN_LAST_5BYTES
};

typedef uint32_t retrophies_emitter_patch_t;

typedef struct retrophies_emitter_t retrophies_emitter_t;

struct retrophies_emitter_t
{
  size_t   code_size;
  size_t   data_size;
  size_t   temp_size;

  uint8_t* code_buffer;
  uint8_t* data_buffer;
  uint8_t* temp_buffer;

  retrophies_emitter_patch_t (*emit)(retrophies_emitter_t* self, int insn, va_list args);
};

void retrophies_emitter_counter(retrophies_emitter_t* emitter);
void retrophies_emitter_generator(retrophies_emitter_t* emitter, void* code_buffer, void* temp_buffer);

retrophies_emitter_patch_t retrophies_emitter_emit(retrophies_emitter_t* emitter, int insn, ...);
retrophies_emitter_patch_t retrophies_emitter_getpc(retrophies_emitter_t* emitter);
void                       retrophies_emitter_patch(retrophies_emitter_t* emitter, retrophies_emitter_patch_t patch);

#endif /* RETROPHIES_EMITTER_H */
