#ifndef RETROPHIES_EMITTER_H
#define RETROPHIES_EMITTER_H

#include <stdarg.h>

enum
{
  /* 1-byte */
  RETROPHIES_INSN_ABS_I32,
  RETROPHIES_INSN_ABS_I64,
  RETROPHIES_INSN_ABS_F32,
  RETROPHIES_INSN_ABS_F64,
  RETROPHIES_INSN_ADD_X32,
  RETROPHIES_INSN_ADD_X64,
  RETROPHIES_INSN_ADD_F32,
  RETROPHIES_INSN_ADD_F64,
  RETROPHIES_INSN_AND_BOOL,
  RETROPHIES_INSN_AND_X32,
  RETROPHIES_INSN_AND_X64,
  RETROPHIES_INSN_CEIL_F32,
  RETROPHIES_INSN_CEIL_F64,
  RETROPHIES_INSN_DIV_I32,
  RETROPHIES_INSN_DIV_I64,
  RETROPHIES_INSN_DIV_U32,
  RETROPHIES_INSN_DIV_U64,
  RETROPHIES_INSN_DIV_F32,
  RETROPHIES_INSN_DIV_F64,
  RETROPHIES_INSN_EQUAL_X32,
  RETROPHIES_INSN_EQUAL_X64,
  RETROPHIES_INSN_EQUAL_F32,
  RETROPHIES_INSN_EQUAL_F64,
  RETROPHIES_INSN_FLOOR_F32,
  RETROPHIES_INSN_FLOOR_F64,
  RETROPHIES_INSN_GREATEREQUAL_I32,
  RETROPHIES_INSN_GREATEREQUAL_I64,
  RETROPHIES_INSN_GREATEREQUAL_U32,
  RETROPHIES_INSN_GREATEREQUAL_U64,
  RETROPHIES_INSN_GREATEREQUAL_F32,
  RETROPHIES_INSN_GREATEREQUAL_F64,
  RETROPHIES_INSN_GREATERTHAN_I32,
  RETROPHIES_INSN_GREATERTHAN_I64,
  RETROPHIES_INSN_GREATERTHAN_U32,
  RETROPHIES_INSN_GREATERTHAN_U64,
  RETROPHIES_INSN_GREATERTHAN_F32,
  RETROPHIES_INSN_GREATERTHAN_F64,
  RETROPHIES_INSN_IDIV_X32,
  RETROPHIES_INSN_IDIV_X64,
  RETROPHIES_INSN_IDIV_U32,
  RETROPHIES_INSN_IDIV_U64,
  RETROPHIES_INSN_LESSEQUAL_I32,
  RETROPHIES_INSN_LESSEQUAL_I64,
  RETROPHIES_INSN_LESSEQUAL_U32,
  RETROPHIES_INSN_LESSEQUAL_U64,
  RETROPHIES_INSN_LESSEQUAL_F32,
  RETROPHIES_INSN_LESSEQUAL_F64,
  RETROPHIES_INSN_LESSTHAN_I32,
  RETROPHIES_INSN_LESSTHAN_I64,
  RETROPHIES_INSN_LESSTHAN_U32,
  RETROPHIES_INSN_LESSTHAN_U64,
  RETROPHIES_INSN_LESSTHAN_F32,
  RETROPHIES_INSN_LESSTHAN_F64,
  RETROPHIES_INSN_MOD_I32,
  RETROPHIES_INSN_MOD_I64,
  RETROPHIES_INSN_MOD_U32,
  RETROPHIES_INSN_MOD_U64,
  RETROPHIES_INSN_MOD_F32,
  RETROPHIES_INSN_MOD_F64,
  RETROPHIES_INSN_MUL_X32,
  RETROPHIES_INSN_MUL_X64,
  RETROPHIES_INSN_MUL_F32,
  RETROPHIES_INSN_MUL_F64,
  RETROPHIES_INSN_NEG_I32,
  RETROPHIES_INSN_NEG_I64,
  RETROPHIES_INSN_NEG_F32,
  RETROPHIES_INSN_NEG_F64,
  RETROPHIES_INSN_NOT,
  RETROPHIES_INSN_NOTEQUAL_X32,
  RETROPHIES_INSN_NOTEQUAL_X64,
  RETROPHIES_INSN_NOTEQUAL_F32,
  RETROPHIES_INSN_NOTEQUAL_F64,
  RETROPHIES_INSN_OR_BOOL,
  RETROPHIES_INSN_OR_X32,
  RETROPHIES_INSN_OR_X64,
  RETROPHIES_INSN_PUSH_0,
  RETROPHIES_INSN_PUSH_1,
  RETROPHIES_INSN_PUSH_2,
  RETROPHIES_INSN_PUSH_10,
  RETROPHIES_INSN_PUSH_16,
  RETROPHIES_INSN_RAND,
  RETROPHIES_INSN_RETURN_X32,
  RETROPHIES_INSN_RETURN_X64,
  RETROPHIES_INSN_SHIFTLEFT_X32,
  RETROPHIES_INSN_SHIFTLEFT_X64,
  RETROPHIES_INSN_SHIFTRIGHT_I32,
  RETROPHIES_INSN_SHIFTRIGHT_I64,
  RETROPHIES_INSN_SHIFTRIGHT_U32,
  RETROPHIES_INSN_SHIFTRIGHT_U64,
  RETROPHIES_INSN_SUB_X32,
  RETROPHIES_INSN_SUB_X64,
  RETROPHIES_INSN_SUB_F32,
  RETROPHIES_INSN_SUB_F64,
  RETROPHIES_INSN_TRUNC_F32,
  RETROPHIES_INSN_TRUNC_F64,
  RETROPHIES_INSN_XOR_BOOL,
  RETROPHIES_INSN_XOR_X32,
  RETROPHIES_INSN_XOR_X64,

  RETROPHIES_INSN_LAST_1BYTE = RETROPHIES_INSN_XOR_X64,

  /* 2-bytes */
  RETROPHIES_INSN_PUSH_I8,
  RETROPHIES_INSN_PUSH_U8,

  RETROPHIES_INSN_LAST_2BYTES = RETROPHIES_INSN_PUSH_U8,
  
  /* 3-bytes */
  RETROPHIES_INSN_GETGLOBAL,
  RETROPHIES_INSN_GETLOCAL,
  RETROPHIES_INSN_PUSH_I16,
  RETROPHIES_INSN_PUSH_U16,
  RETROPHIES_INSN_SETGLOBAL,
  RETROPHIES_INSN_SETLOCAL,
  RETROPHIES_INSN_SYSTEM,

  RETROPHIES_INSN_LAST_3BYTES = RETROPHIES_INSN_SYSTEM,

  /* 5-bytes */
  RETROPHIES_INSN_CALL,
  RETROPHIES_INSN_CHECKFOR_I32,
  RETROPHIES_INSN_CHECKFOR_I64,
  RETROPHIES_INSN_CHECKFOR_U32,
  RETROPHIES_INSN_CHECKFOR_U64,
  RETROPHIES_INSN_CHECKFOR_F32,
  RETROPHIES_INSN_CHECKFOR_F64,
  RETROPHIES_INSN_JE,
  RETROPHIES_INSN_JNE,
  RETROPHIES_INSN_JUMP,
  RETROPHIES_INSN_NEXT_I32,
  RETROPHIES_INSN_NEXT_I64,
  RETROPHIES_INSN_NEXT_U32,
  RETROPHIES_INSN_NEXT_U64,
  RETROPHIES_INSN_NEXT_F32,
  RETROPHIES_INSN_NEXT_F64,
  RETROPHIES_INSN_PUSH_I32,
  RETROPHIES_INSN_PUSH_U32,
  RETROPHIES_INSN_PUSH_F32,
  
  RETROPHIES_INSN_LAST_5BYTES = RETROPHIES_INSN_PUSH_F32,

  /* 7-bytes */
  RETROPHIES_INSN_PUSH_I64,
  RETROPHIES_INSN_PUSH_U64,
  RETROPHIES_INSN_PUSH_F64,

  RETROPHIES_INSN_LAST_7BYTES = RETROPHIES_INSN_PUSH_F64
};

enum
{
  RETROPHIES_SYSTEM_AWARD,
  RETROPHIES_SYSTEM_MEMSCAN
};

int  retrophies_emitter_size(int insn);
void retrophies_emitter_emit(void* buffer, int insn, va_list args);
void retrophies_emitter_patch(void* jump, int label);

#endif /* RETROPHIES_EMITTER_H */
